import type { Product, Order } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Adobe Creative Cloud",
    slug: "adobe-creative-cloud",
    description: "Accédez à plus de 20 applications créatives dont Photoshop, Illustrator, Premiere Pro et After Effects. Licence annuelle avec mises à jour automatiques et 100 Go de stockage cloud inclus.",
    shortDescription: "Suite complète d'outils créatifs professionnels",
    price: 29.99,
    originalPrice: 54.99,
    currency: "EUR",
    category: "subscription",
    categoryLabel: "Abonnement",
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=300&fit=crop",
    badge: "-45%",
    rating: 4.8,
    reviewCount: 2341,
    features: ["20+ applications", "100 Go cloud", "Mises à jour auto", "Support 24/7"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "2",
    name: "Netflix Premium 12 Mois",
    slug: "netflix-premium-12-mois",
    description: "Carte cadeau Netflix Premium pour 12 mois. Streaming illimité en 4K Ultra HD sur 4 écrans simultanés. Compatible avec tous les appareils.",
    shortDescription: "12 mois de streaming illimité en 4K",
    price: 119.99,
    originalPrice: 215.88,
    currency: "EUR",
    category: "gift-card",
    categoryLabel: "Carte Cadeau",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8d7e28?w=400&h=300&fit=crop",
    badge: "Best-seller",
    rating: 4.9,
    reviewCount: 5420,
    features: ["4K Ultra HD", "4 écrans", "Tous appareils", "Sans engagement"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "3",
    name: "Windows 11 Pro",
    slug: "windows-11-pro",
    description: "Licence Windows 11 Professionnel à vie. Activation en ligne immédiate. Compatible avec les derniers processeurs et sécurité renforcée avec TPM 2.0.",
    shortDescription: "Licence à vie Windows 11 Professionnel",
    price: 14.99,
    originalPrice: 259.00,
    currency: "EUR",
    category: "license",
    categoryLabel: "Licence",
    image: "https://images.unsplash.com/photo-1624571409024-381b6d071b8a?w=400&h=300&fit=crop",
    badge: "-94%",
    rating: 4.7,
    reviewCount: 8932,
    features: ["Activation à vie", "Support Microsoft", "Mises à jour", "Sécurité TPM"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "4",
    name: "Spotify Premium 6 Mois",
    slug: "spotify-premium-6-mois",
    description: "Profitez de 6 mois de musique sans publicité, avec téléchargement hors ligne et qualité audio supérieure.",
    shortDescription: "6 mois de musique sans pub",
    price: 44.99,
    originalPrice: 59.94,
    currency: "EUR",
    category: "gift-card",
    categoryLabel: "Carte Cadeau",
    image: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
    rating: 4.6,
    reviewCount: 1876,
    features: ["Sans publicité", "Hors ligne", "Qualité HD", "Podcasts inclus"],
    deliveryType: "email",
    inStock: true,
  },
  {
    id: "5",
    name: "NordVPN 2 Ans",
    slug: "nordvpn-2-ans",
    description: "Protection VPN premium pendant 2 ans. Plus de 5500 serveurs dans 60 pays. Connexion ultra-rapide et chiffrement militaire.",
    shortDescription: "VPN premium 2 ans — 5500+ serveurs",
    price: 79.99,
    originalPrice: 286.80,
    currency: "EUR",
    category: "subscription",
    categoryLabel: "Abonnement",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=400&h=300&fit=crop",
    badge: "-72%",
    rating: 4.5,
    reviewCount: 3210,
    features: ["5500+ serveurs", "60 pays", "Chiffrement AES-256", "6 appareils"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "6",
    name: "Microsoft Office 2024",
    slug: "microsoft-office-2024",
    description: "Suite bureautique complète avec Word, Excel, PowerPoint et Outlook. Licence perpétuelle pour 1 PC.",
    shortDescription: "Suite bureautique complète — licence à vie",
    price: 34.99,
    originalPrice: 149.00,
    currency: "EUR",
    category: "license",
    categoryLabel: "Licence",
    image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=400&h=300&fit=crop",
    badge: "-76%",
    rating: 4.8,
    reviewCount: 6540,
    features: ["Word, Excel, PPT", "Licence à vie", "1 PC", "Support inclus"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "7",
    name: "PlayStation Plus 12 Mois",
    slug: "playstation-plus-12-mois",
    description: "Abonnement PlayStation Plus Essential pour 12 mois. Jeux mensuels gratuits, multijoueur en ligne et réductions exclusives.",
    shortDescription: "12 mois de jeux et multijoueur en ligne",
    price: 49.99,
    originalPrice: 59.99,
    currency: "EUR",
    category: "activation-key",
    categoryLabel: "Clé d'activation",
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=300&fit=crop",
    rating: 4.4,
    reviewCount: 2100,
    features: ["Jeux mensuels", "Multijoueur", "Réductions", "Cloud saves"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "8",
    name: "Canva Pro Annuel",
    slug: "canva-pro-annuel",
    description: "Accès Canva Pro pendant 1 an. Plus de 100 millions de photos, vidéos et éléments graphiques. Création illimitée avec outils IA.",
    shortDescription: "Design illimité avec IA pendant 1 an",
    price: 54.99,
    originalPrice: 109.99,
    currency: "EUR",
    category: "saas",
    categoryLabel: "SaaS",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=300&fit=crop",
    badge: "-50%",
    rating: 4.7,
    reviewCount: 1540,
    features: ["100M+ assets", "Outils IA", "Brand Kit", "5 membres"],
    deliveryType: "instant",
    inStock: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-2024-001",
    date: "2024-12-15",
    items: [{ product: products[0], quantity: 1 }],
    total: 29.99,
    status: "completed",
    deliveryCode: "ACC-XXXX-YYYY-ZZZZ",
  },
  {
    id: "ORD-2024-002",
    date: "2024-12-10",
    items: [{ product: products[2], quantity: 1 }, { product: products[5], quantity: 1 }],
    total: 49.98,
    status: "completed",
    deliveryCode: "WIN-ABCD-EFGH-IJKL",
  },
  {
    id: "ORD-2024-003",
    date: "2024-12-01",
    items: [{ product: products[1], quantity: 1 }],
    total: 119.99,
    status: "pending",
  },
];

export const categories = [
  { value: "all", label: "Tous les produits" },
  { value: "subscription", label: "Abonnements" },
  { value: "gift-card", label: "Cartes Cadeau" },
  { value: "license", label: "Licences" },
  { value: "activation-key", label: "Clés d'activation" },
  { value: "saas", label: "SaaS" },
  { value: "downloadable", label: "Téléchargeables" },
];
