import type { Product, Order } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Netflix Premium 12 Mois",
    slug: "netflix-premium-12-mois",
    description: "Carte cadeau Netflix Premium pour 12 mois. Streaming illimité en 4K Ultra HD sur 4 écrans simultanés. Compatible avec tous les appareils. Activation instantanée sur votre compte Netflix.",
    shortDescription: "12 mois de streaming illimité en 4K",
    price: 18000,
    originalPrice: 24000,
    currency: "DZD",
    category: "gift-card",
    categoryLabel: "Carte Cadeau",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8d7e28?w=400&h=300&fit=crop",
    badge: "Best-seller",
    rating: 4.9,
    reviewCount: 5420,
    features: ["4K Ultra HD", "4 écrans simultanés", "Tous appareils", "Sans engagement"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "2",
    name: "Spotify Premium 12 Mois",
    slug: "spotify-premium-12-mois",
    description: "Profitez de 12 mois de musique sans publicité, avec téléchargement hors ligne et qualité audio supérieure. Compatible Algérie. Activation immédiate.",
    shortDescription: "12 mois de musique sans pub, qualité HD",
    price: 8500,
    originalPrice: 12000,
    currency: "DZD",
    category: "gift-card",
    categoryLabel: "Carte Cadeau",
    image: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=300&fit=crop",
    badge: "-29%",
    rating: 4.7,
    reviewCount: 3100,
    features: ["Sans publicité", "Écoute hors ligne", "Qualité HD", "Podcasts inclus"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "3",
    name: "Windows 11 Pro — Licence à vie",
    slug: "windows-11-pro",
    description: "Licence Windows 11 Professionnel à vie. Activation en ligne immédiate. Compatible avec les derniers processeurs et sécurité renforcée avec TPM 2.0. Clé officielle Microsoft.",
    shortDescription: "Licence à vie Windows 11 Professionnel",
    price: 4500,
    originalPrice: 35000,
    currency: "DZD",
    category: "license",
    categoryLabel: "Licence",
    image: "https://images.unsplash.com/photo-1624571409024-381b6d071b8a?w=400&h=300&fit=crop",
    badge: "-87%",
    rating: 4.8,
    reviewCount: 8932,
    features: ["Activation à vie", "Support Microsoft", "Mises à jour", "Sécurité TPM 2.0"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "4",
    name: "Microsoft Office 2024 Pro",
    slug: "microsoft-office-2024",
    description: "Suite bureautique complète avec Word, Excel, PowerPoint et Outlook. Licence perpétuelle pour 1 PC. Clé officielle avec activation en ligne.",
    shortDescription: "Suite bureautique complète — licence à vie",
    price: 6500,
    originalPrice: 25000,
    currency: "DZD",
    category: "license",
    categoryLabel: "Licence",
    image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=400&h=300&fit=crop",
    badge: "-74%",
    rating: 4.8,
    reviewCount: 6540,
    features: ["Word, Excel, PowerPoint", "Licence à vie", "1 PC", "Support inclus"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "5",
    name: "PlayStation Plus Essential 12 Mois",
    slug: "playstation-plus-12-mois",
    description: "Abonnement PlayStation Plus Essential pour 12 mois. Jeux mensuels gratuits, multijoueur en ligne et réductions exclusives. Code région compatible Algérie.",
    shortDescription: "12 mois de jeux et multijoueur en ligne",
    price: 9000,
    originalPrice: 12000,
    currency: "DZD",
    category: "activation-key",
    categoryLabel: "Clé d'activation",
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=300&fit=crop",
    badge: "-25%",
    rating: 4.5,
    reviewCount: 2100,
    features: ["Jeux mensuels gratuits", "Multijoueur en ligne", "Réductions PS Store", "Cloud saves"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "6",
    name: "Xbox Game Pass Ultimate 3 Mois",
    slug: "xbox-game-pass-ultimate-3-mois",
    description: "Accédez à plus de 400 jeux sur console, PC et mobile. Inclut Xbox Live Gold, EA Play et les sorties Day One. Code compatible Algérie.",
    shortDescription: "400+ jeux sur console, PC et cloud",
    price: 5500,
    originalPrice: 7500,
    currency: "DZD",
    category: "activation-key",
    categoryLabel: "Clé d'activation",
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=300&fit=crop",
    rating: 4.6,
    reviewCount: 1870,
    features: ["400+ jeux", "Xbox Live Gold", "EA Play inclus", "Cloud Gaming"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "7",
    name: "Canva Pro — 1 An",
    slug: "canva-pro-annuel",
    description: "Accès Canva Pro pendant 1 an. Plus de 100 millions de photos, vidéos et éléments graphiques. Création illimitée avec outils IA intégrés. Idéal pour les créateurs de contenu en Algérie.",
    shortDescription: "Design illimité avec IA pendant 1 an",
    price: 7000,
    originalPrice: 14000,
    currency: "DZD",
    category: "saas",
    categoryLabel: "SaaS",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=300&fit=crop",
    badge: "-50%",
    rating: 4.7,
    reviewCount: 1540,
    features: ["100M+ ressources", "Outils IA", "Brand Kit", "5 membres d'équipe"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "8",
    name: "Adobe Creative Cloud 1 An",
    slug: "adobe-creative-cloud",
    description: "Accédez à plus de 20 applications créatives dont Photoshop, Illustrator, Premiere Pro et After Effects. Licence annuelle avec mises à jour automatiques et 100 Go de stockage cloud.",
    shortDescription: "Suite complète d'outils créatifs Adobe",
    price: 25000,
    originalPrice: 45000,
    currency: "DZD",
    category: "subscription",
    categoryLabel: "Abonnement",
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=300&fit=crop",
    badge: "-44%",
    rating: 4.8,
    reviewCount: 2341,
    features: ["20+ applications", "100 Go cloud", "Mises à jour auto", "Support 24/7"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "9",
    name: "NordVPN — 2 Ans",
    slug: "nordvpn-2-ans",
    description: "Protection VPN premium pendant 2 ans. Plus de 5500 serveurs dans 60 pays. Connexion ultra-rapide et chiffrement militaire AES-256. Idéal pour naviguer en toute sécurité depuis l'Algérie.",
    shortDescription: "VPN premium 2 ans — 5500+ serveurs",
    price: 10500,
    originalPrice: 36000,
    currency: "DZD",
    category: "subscription",
    categoryLabel: "Abonnement",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=400&h=300&fit=crop",
    badge: "-71%",
    rating: 4.5,
    reviewCount: 3210,
    features: ["5500+ serveurs", "60 pays", "Chiffrement AES-256", "6 appareils"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "10",
    name: "IPTV Premium 12 Mois",
    slug: "iptv-premium-12-mois",
    description: "Accès IPTV Premium pendant 12 mois. Plus de 10 000 chaînes en direct, films et séries en qualité HD/4K. Compatible Smart TV, Android, iOS et PC. Chaînes arabes, françaises et sportives incluses.",
    shortDescription: "10 000+ chaînes TV et VOD en HD/4K",
    price: 6000,
    originalPrice: 10000,
    currency: "DZD",
    category: "premium-access",
    categoryLabel: "Accès Premium",
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&h=300&fit=crop",
    badge: "-40%",
    rating: 4.3,
    reviewCount: 4200,
    features: ["10 000+ chaînes", "HD & 4K", "Chaînes arabes & FR", "Multi-appareil"],
    deliveryType: "instant",
    inStock: true,
    popular: true,
  },
  {
    id: "11",
    name: "Carte Google Play 5000 DA",
    slug: "carte-google-play-5000da",
    description: "Carte cadeau Google Play de 5000 DA. Utilisable pour acheter des applications, jeux, films, livres et musique sur le Google Play Store. Code valable en Algérie.",
    shortDescription: "Crédit Google Play Store — 5000 DA",
    price: 5500,
    currency: "DZD",
    category: "gift-card",
    categoryLabel: "Carte Cadeau",
    image: "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=400&h=300&fit=crop",
    rating: 4.6,
    reviewCount: 1230,
    features: ["Apps & Jeux", "Films & Séries", "Livres", "Compatible Algérie"],
    deliveryType: "instant",
    inStock: true,
  },
  {
    id: "12",
    name: "Kaspersky Total Security 1 An",
    slug: "kaspersky-total-security",
    description: "Protection complète pour 3 appareils pendant 1 an. Antivirus, anti-malware, pare-feu, VPN intégré et gestionnaire de mots de passe. Licence officielle avec activation en ligne.",
    shortDescription: "Antivirus complet pour 3 appareils — 1 an",
    price: 3500,
    originalPrice: 8000,
    currency: "DZD",
    category: "license",
    categoryLabel: "Licence",
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=300&fit=crop",
    badge: "-56%",
    rating: 4.4,
    reviewCount: 980,
    features: ["3 appareils", "Anti-malware", "VPN intégré", "Gestionnaire mdp"],
    deliveryType: "instant",
    inStock: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: "CMD-2025-001",
    date: "2025-04-05",
    items: [{ product: products[0], quantity: 1 }],
    total: 18000,
    status: "completed",
    deliveryCode: "NFLX-XXXX-YYYY-ZZZZ",
  },
  {
    id: "CMD-2025-002",
    date: "2025-03-28",
    items: [{ product: products[2], quantity: 1 }, { product: products[3], quantity: 1 }],
    total: 11000,
    status: "completed",
    deliveryCode: "WIN-ABCD-EFGH-IJKL",
  },
  {
    id: "CMD-2025-003",
    date: "2025-03-15",
    items: [{ product: products[9], quantity: 1 }],
    total: 6000,
    status: "pending",
  },
];

export const categories = [
  { value: "all", label: "Tous les produits" },
  { value: "subscription", label: "Abonnements" },
  { value: "gift-card", label: "Cartes Cadeau" },
  { value: "license", label: "Licences" },
  { value: "activation-key", label: "Clés d'activation" },
  { value: "premium-access", label: "Accès Premium" },
  { value: "saas", label: "SaaS" },
  { value: "downloadable", label: "Téléchargeables" },
];
